//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ron_Financial_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class systemuser
    {
        public long Id { get; set; }
        public string UserID { get; set; }
        public int GroupID { get; set; }
        [DisplayName("User Name")]
        [Required(ErrorMessage = "Please Enter UserName")]
        public string UserName { get; set; }
        public string FullName { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Please Enter Password")]
        public string Password { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Createdby { get; set; }
        public Nullable<int> UserStatus { get; set; }
        public int Fosa_Id { get; set; }
        public System.DateTime Password_Expiry_date { get; set; }
        public long organisation_branches_id { get; set; }
        public int Work_Station_Id { get; set; }
        public String LoginErrorMessage { get; set; }

    }
}
